/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/vfJJOMazQfM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Cormorant_Garamond } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

cormorant_garamond({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Button } from "@/components/ui/button"
import { Label } from "@/components/ui/label"
import { Input } from "@/components/ui/input"
import { Select } from "@/components/ui/select"
import { JSX, SVGProps } from "react"

export function sdf() {
  return (
    <div className="px-4 md:px-6 lg:px-8 py-6 space-y-6">
      <div className="flex items-center space-x-4">
        <Button className="rounded-full">
          <ChevronLeftIcon className="w-5 h-5" />
          <span className="sr-only">Back</span>
        </Button>
        <h1 className="text-2xl font-bold tracking-tighter">Регистрация</h1>
      </div>
      <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="login">Логин</Label>
            <Input id="login" placeholder="Логин" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="password">Пароль</Label>
            <Input id="password" placeholder="Пароль" required type="password" />
          </div>
          <div className="space-y-2">
            <Label htmlFor="first-name">Имя</Label>
            <Input id="first-name" placeholder="Имя" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="last-name">Фамилия</Label>
            <Input id="last-name" placeholder="Фамилия" required />
          </div>
          <div className="space-y-2">
            <Label htmlFor="middle-name">Отчество</Label>
            <Input id="middle-name" placeholder="Отчество" />
          </div>
        </div>
        <div className="space-y-4">
          <div className="space-y-2">
            <Label htmlFor="age">Возраст</Label>
            <Select className="w-full" id="age" required>
              <div>Выберите возраст</div>
              <div>18-25</div>
              <div>26-35</div>
              <div>36-50</div>
              <div>50+</div>
            </Select>
          </div>
          <div className="border-dashed border-2 border-gray-300 dark:border-gray-700 rounded-lg p-4 flex items-center justify-center w-full">
            <div className="w-12 h-12 rounded-full overflow-hidden">
              <img
                alt="Avatar placeholder"
                height="64"
                src="/placeholder.svg"
                style={{
                  aspectRatio: "64/64",
                  objectFit: "cover",
                }}
                width="64"
              />
            </div>
            <div className="ml-4 text-sm">
              <p className="font-semibold">Перетащите файл сюда</p>
              <p className="text-gray-500 dark:text-gray-400">
                или
                <Label as="span" className="cursor-pointer underline ml-1" htmlFor="file">
                  выберите файл
                </Label>
              </p>
              <Input className="hidden" id="file" type="file" />
            </div>
          </div>
          <div className="space-y-2">
            <Label>Выберите должность</Label>
            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label>Менеджер</Label>
              </div>
              <div>
                <Label>Разработчик</Label>
              </div>
            </div>
          </div>
        </div>
      </div>
      <Button className="w-full">Зарегистрироваться</Button>
    </div>
  )
}

function ChevronLeftIcon(props: JSX.IntrinsicAttributes & SVGProps<SVGSVGElement>) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m15 18-6-6 6-6" />
    </svg>
  )
}
