/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/bUgf9ocmIbq
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Arimo } from 'next/font/google'
import { Libre_Franklin } from 'next/font/google'

arimo({
  subsets: ['latin'],
  display: 'swap',
})

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
import { Input } from "@/components/ui/input"
import { CardTitle, CardDescription, CardContent, Card } from "@/components/ui/card"
import Link from "next/link"

export function Component() {
  return (
    <main className="flex flex-col items-center justify-center min-h-screen bg-gray-100 dark:bg-gray-800 p-4">
      <div className="max-w-3xl w-full">
        <Input
          className="w-full px-4 py-3 rounded-lg shadow-md bg-white dark:bg-gray-950 dark:text-gray-50 focus:outline-none focus:ring-2 focus:ring-primary-500"
          placeholder="Найти проекты"
        />
      </div>
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-6 mt-8 w-full max-w-6xl">
        <Card>
          <img
            alt="Project Image"
            className="rounded-t-lg object-cover w-full aspect-[4/3]"
            height={250}
            src="/placeholder.svg"
            width={400}
          />
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <CardTitle>Project 1</CardTitle>
              <CardDescription>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</CardDescription>
            </div>
            <Link
              className="inline-flex items-center justify-center h-9 px-4 rounded-md bg-primary-500 text-white hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800"
              href="#"
            >
              Подробнее
            </Link>
          </CardContent>
        </Card>
        <Card>
          <img
            alt="Project Image"
            className="rounded-t-lg object-cover w-full aspect-[4/3]"
            height={250}
            src="/placeholder.svg"
            width={400}
          />
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <CardTitle>Project 2</CardTitle>
              <CardDescription>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</CardDescription>
            </div>
            <Link
              className="inline-flex items-center justify-center h-9 px-4 rounded-md bg-primary-500 text-white hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800"
              href="#"
            >
              Подробнее
            </Link>
          </CardContent>
        </Card>
        <Card>
          <img
            alt="Project Image"
            className="rounded-t-lg object-cover w-full aspect-[4/3]"
            height={250}
            src="/placeholder.svg"
            width={400}
          />
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <CardTitle>Project 3</CardTitle>
              <CardDescription>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</CardDescription>
            </div>
            <Link
              className="inline-flex items-center justify-center h-9 px-4 rounded-md bg-primary-500 text-white hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800"
              href="#"
            >
              Подробнее
            </Link>
          </CardContent>
        </Card>
        <Card>
          <img
            alt="Project Image"
            className="rounded-t-lg object-cover w-full aspect-[4/3]"
            height={250}
            src="/placeholder.svg"
            width={400}
          />
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <CardTitle>Project 4</CardTitle>
              <CardDescription>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</CardDescription>
            </div>
            <Link
              className="inline-flex items-center justify-center h-9 px-4 rounded-md bg-primary-500 text-white hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800"
              href="#"
            >
              Подробнее
            </Link>
          </CardContent>
        </Card>
        <Card>
          <img
            alt="Project Image"
            className="rounded-t-lg object-cover w-full aspect-[4/3]"
            height={250}
            src="/placeholder.svg"
            width={400}
          />
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <CardTitle>Project 5</CardTitle>
              <CardDescription>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</CardDescription>
            </div>
            <Link
              className="inline-flex items-center justify-center h-9 px-4 rounded-md bg-primary-500 text-white hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800"
              href="#"
            >
              Подробнее
            </Link>
          </CardContent>
        </Card>
        <Card>
          <img
            alt="Project Image"
            className="rounded-t-lg object-cover w-full aspect-[4/3]"
            height={250}
            src="/placeholder.svg"
            width={400}
          />
          <CardContent className="p-4 flex flex-col justify-between">
            <div>
              <CardTitle>Project 6</CardTitle>
              <CardDescription>Lorem ipsum dolor sit amet, consectetur adipiscing elit.</CardDescription>
            </div>
            <Link
              className="inline-flex items-center justify-center h-9 px-4 rounded-md bg-primary-500 text-white hover:bg-primary-600 focus:outline-none focus:ring-2 focus:ring-primary-500 focus:ring-offset-2 dark:focus:ring-offset-gray-800"
              href="#"
            >
              Подробнее
            </Link>
          </CardContent>
        </Card>
      </div>
    </main>
  )
}
