/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/gyuCqesDDaM
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/
import { Button } from "@/components/ui/button"

export function Component() {
  return (
    <main className="flex h-screen">
      <aside className="w-60 bg-gray-100 p-4 space-y-4">
        <header className="flex items-center space-x-2">
          <RocketIcon className="text-blue-500" />
          <span>Teams in Space</span>
        </header>
        <nav className="space-y-2">
          <Button className="w-full justify-start">Roadmap</Button>
          <Button className="w-full justify-start bg-blue-500 text-white">Active sprints</Button>
          <Button className="w-full justify-start">Reports</Button>
          <Button className="w-full justify-start">Issues</Button>
        </nav>
      </aside>
      <section className="flex-1 p-4">
        <div className="flex justify-between mb-4">
          <h1 className="text-2xl font-bold">Board</h1>
          <Button variant="secondary">Release</Button>
        </div>
        <div className="grid grid-cols-3 gap-4">
          <article className="bg-white p-4 rounded-lg">
            <h2 className="font-semibold mb-2">TO DO 5</h2>
            <ul className="space-y-2">
              <li>Engage Jupiter Express for outer solar system travel</li>
              <li>Create 90 day plans for all departments in the Mars Office</li>
              <li>Engage Saturn's Rings Resort as a preferred provider</li>
            </ul>
          </article>
          <article className="bg-white p-4 rounded-lg">
            <h2 className="font-semibold mb-2">IN PROGRESS 5</h2>
            <ul className="space-y-2">
              <li>{`Requesting available flights is now taking > 5 seconds`}</li>
              <li>Engage Saturn Shuttle Lines for group tours</li>
              <li>Establish a catering vendor to provide meal service</li>
            </ul>
          </article>
          <article className="bg-white p-4 rounded-lg">
            <h2 className="font-semibold mb-2">DONE 8</h2>
            <ul className="space-y-2">
              <li>Homepage footer uses an inline style - should use a class</li>
              <li>Engage JetShuttle SpaceWays for travel</li>
              <li>Establish a catering vendor to provide meal service</li>
            </ul>
          </article>
        </div>
      </section>
    </main>
  )
}

function RocketIcon(props) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M4.5 16.5c-1.5 1.26-2 5-2 5s3.74-.5 5-2c.71-.84.7-2.13-.09-2.91a2.18 2.18 0 0 0-2.91-.09z" />
      <path d="m12 15-3-3a22 22 0 0 1 2-3.95A12.88 12.88 0 0 1 22 2c0 2.72-.78 7.5-6 11a22.35 22.35 0 0 1-4 2z" />
      <path d="M9 12H4s.55-3.03 2-4c1.62-1.08 5 0 5 0" />
      <path d="M12 15v5s3.03-.55 4-2c1.08-1.62 0-5 0-5" />
    </svg>
  )
}
