/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/9DZuxeFZ69q
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Archivo } from 'next/font/google'
import { Arimo } from 'next/font/google'

archivo({
  subsets: ['latin'],
  display: 'swap',
})

arimo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/

/** Add border radius CSS variable to your global CSS:

:root {
  --radius: 0.875rem;
}
**/
import { Input } from "@/components/ui/input"
import { AvatarImage, AvatarFallback, Avatar } from "@/components/ui/avatar"

export function newComs() {
  return (
    <section className="w-full py-12 md:py-24 lg:py-32">
      <div className="container px-4 md:px-6">
        <div className="flex flex-col items-center justify-center gap-6">
          <div className="w-full max-w-xl">
            <Input placeholder="Search users..." />
          </div>
          <div className="grid grid-cols-1 gap-6 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4">
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <div className="flex flex-col items-center justify-center p-6 bg-white dark:bg-gray-950">
                <Avatar>
                  <AvatarImage alt="@shadcn" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>CN</AvatarFallback>
                </Avatar>
                <div className="mt-4 text-center">
                  <h3 className="text-lg font-bold">Olivia Davis</h3>
                  <p className="text-gray-500 dark:text-gray-400">Product Manager</p>
                  <p className="text-sm line-clamp-2 mt-2">
                    Experienced product manager with a passion for building innovative solutions. Skilled in user
                    research, product strategy, and cross-functional collaboration.
                  </p>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <div className="flex flex-col items-center justify-center p-6 bg-white dark:bg-gray-950">
                <Avatar>
                  <AvatarImage alt="@jaredpalmer" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>JP</AvatarFallback>
                </Avatar>
                <div className="mt-4 text-center">
                  <h3 className="text-lg font-bold">Jared Palmer</h3>
                  <p className="text-gray-500 dark:text-gray-400">Software Engineer</p>
                  <p className="text-sm line-clamp-2 mt-2">
                    Talented software engineer with expertise in full-stack web development. Passionate about building
                    scalable and user-friendly applications.
                  </p>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <div className="flex flex-col items-center justify-center p-6 bg-white dark:bg-gray-950">
                <Avatar>
                  <AvatarImage alt="@maxleiter" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>ML</AvatarFallback>
                </Avatar>
                <div className="mt-4 text-center">
                  <h3 className="text-lg font-bold">Max Leiter</h3>
                  <p className="text-gray-500 dark:text-gray-400">UI/UX Designer</p>
                  <p className="text-sm line-clamp-2 mt-2">
                    Experienced UI/UX designer with a keen eye for detail and a passion for creating intuitive and
                    visually appealing user experiences.
                  </p>
                </div>
              </div>
            </div>
            <div className="relative group overflow-hidden rounded-lg shadow-lg hover:shadow-xl transition-transform duration-300 ease-in-out hover:-translate-y-2">
              <div className="flex flex-col items-center justify-center p-6 bg-white dark:bg-gray-950">
                <Avatar>
                  <AvatarImage alt="@shuding_" src="/placeholder-avatar.jpg" />
                  <AvatarFallback>SD</AvatarFallback>
                </Avatar>
                <div className="mt-4 text-center">
                  <h3 className="text-lg font-bold">Shu Ding</h3>
                  <p className="text-gray-500 dark:text-gray-400">Frontend Engineer</p>
                  <p className="text-sm line-clamp-2 mt-2">
                    Skilled frontend engineer with a strong background in React and modern web development. Passionate
                    about building high-performance and accessible user interfaces.
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  )
}
